sudo: required

arch:
  #repos:
  packages:
    # pacman packages
    - cmake
    - clang
    - libsodium
    - ninja
    # aur packages
  script:
    - "CXX=clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release"
    - "ninja"
    - "ctest"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
